name: OpenAIWhisper
channels:
  - conda-forge
dependencies:
  - ffmpeg
  - python
  - youtube-dl
  - pip
  - ipython
  - jupyter
  - google-colab
  - pandas
  - mutagen
  - pip:
    - git+https://github.com/openai/whisper.git 
